[package]
name = "c_side_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
actix-web-actors = "4.3.1"
env_logger = "0.11.5"
reqwest = "0.12.5"
serde = { version = "1.0.208", features = ["derive"] }
tokio = "1.39.3"
